default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

production:
  <<: *default
  database: flixter_production
username: flixter
password: <%= ENV['FLIXTER_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: flixter_development

test:
  <<: *default
  database: flixter_test
